docs/quickstart.rst

- Added initialization code to every example, to make it easier for developers to cut-and-paste code
- Added comment on how to create an API key to every initializer 
- Corrected syntax for `activate_user()`
- Updated example loop code in the **Loop through a list** section to a "do/while" style of loop
- Added code to user loop to show how to access commonly used profile attributes

Update Quckstart examples

---

okta/framework/Serializer.py
okta/framework/Utils.py

:bug: Fixes serialization method to include `alt_names` when rebuilding API request

:bug: Fix serialization method

---

okta/UsersClient.py

:seedling: Adds suspend, unsuspend, and reset factors API calls
Fixes: #14 
Resolves: OKTA-117658

:seedling: Adds suspend, unsuspend, and reset factors api calls

---

okta/AppInstanceClient.py
okta/AuthClient.py
okta/EventsClient.py
okta/FactorsAdminClient.py
okta/FactorsClient.py
okta/SessionsClient.py
okta/UserGroupsClient.py
okta/UsersClient.py
okta/framework/ApiClient.py
tests/AppInstanceClientTest.py
tests/AuthClientTest.py
tests/EventsClientTest.py
tests/FactorsAdminClientTest.py
tests/FactorsClientTest.py
tests/SessionsClientTest.py
tests/UserGroupsClientTest.py
tests/UsersClientTest.py

✅ Adds basic client initializing tests

:white_check_mark: Adds basic client tests

---

okta/UsersClient.py
okta/models/user/AppLinks.py
okta/models/user/__init__.py
tests/SerializationTest.py

Added method to get appLinks for a given user

---

setup.py

there is not a README.rst file.

spelling correction

---

okta/cache/cache.py
okta/cache/okta_cache.py
okta/client.py
okta/config/config_setter.py
okta/errors/http_error.py
okta/errors/okta_api_error.py
okta/http_client.py
okta/jwt.py
okta/oauth.py
okta/request_executor.py
tests/unit/cassettes/test_client_error_call_SSWS.yaml
tests/unit/cassettes/test_client_error_call_oauth.yaml
tests/unit/test_cache.py
tests/unit/test_client.py
tests/unit/test_http_client.py

- Client can be built with OAuth or SSWS configuration
- Can make call and parse response
- For tickets [297423](https://oktainc.atlassian.net/browse/OKTA-297423?atlOrigin=eyJpIjoiMThhZDQyZmNkZWVhNDZmM2I2ZDcyOGRjZWExNDZmNGIiLCJwIjoiaiJ9) and [297422](https://oktainc.atlassian.net/browse/OKTA-297422?atlOrigin=eyJpIjoiZjVjOWRkMzA2ZWJkNGEyY2E2ZGU2ZmI3YzMyMWVjZDciLCJwIjoiaiJ9)

SSWS & OAuth support

---

okta/api_response.py
okta/cache/okta_cache.py
okta/http_client.py
okta/request_executor.py
tests/mocks.py
tests/unit/cassettes/test_client_error_call_SSWS.yaml
tests/unit/cassettes/test_client_error_call_oauth.yaml
tests/unit/test_api_response.py
tests/unit/test_http_client.py
tests/unit/test_oauth.py

- Implemented paging mechanism for easy retrieval of next pages
- Refactored and updated unit tests
Resolves [OKTA-297429](https://oktainc.atlassian.net/browse/OKTA-297429?atlOrigin=eyJpIjoiZjM4MGVkMGI2MTYyNDUzZjk3YjY3NDFhMmU1NTExYzMiLCJwIjoiaiJ9)

API Pagination

---

tests/integration/cassettes/TestGroupsResource.test_group_assigned_applications.yaml
tests/integration/cassettes/TestGroupsResource.test_group_target_add.yaml
tests/integration/test_groups_it.py

- All tests pass now (Including ones including Apps)

Groups Integration Tests Upgrade

---

tests/integration/cassettes/TestAuthorizationServerResource.test_activate_server.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_create_auth_server.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_create_get_oauth2_claim.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_create_get_oauth2_scope.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_delete_auth_server_policy.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_delete_oauth2_claim.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_delete_oauth2_scope.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_get_auth_server_policy.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_get_created_auth_server.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_list_auth_server_keys.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_list_auth_server_policies.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_list_auth_servers.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_list_oauth2_claims.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_list_oauth2_scopes.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_rotate_auth_server_keys.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_update_auth_server.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_update_auth_server_policy.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_update_deactivate_delete_server.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_update_oauth2_claim.yaml
tests/integration/cassettes/TestAuthorizationServerResource.test_update_oauth2_scope.yaml
tests/integration/test_auth_server_it.py

Tests are in: `tests/integration/test_auth_server_it.py`

Completed Authorization Server Integration Tests

---

okta/okta_object.py
okta/resource_clients/event_hook_client.py
tests/integration/cassettes/TestEventHooksResource.test_activate_event_hook.yaml
tests/integration/cassettes/TestEventHooksResource.test_create_get_event_hook.yaml
tests/integration/cassettes/TestEventHooksResource.test_deactivate_event_hook.yaml
tests/integration/cassettes/TestEventHooksResource.test_delete_event_hook.yaml
tests/integration/cassettes/TestEventHooksResource.test_list_event_hooks.yaml
tests/integration/cassettes/TestEventHooksResource.test_update_event_hook.yaml
tests/integration/test_event_hooks_it.py
tests/utils.py

Tests are in `tests/integration/test_event_hooks_it.py`

Completed Event Hooks Integration Tests

---

tests/integration/cassettes/TestFeaturesResource.test_get_feature.yaml
tests/integration/cassettes/TestFeaturesResource.test_list_feature_dependencies.yaml
tests/integration/cassettes/TestFeaturesResource.test_list_feature_dependents.yaml
tests/integration/cassettes/TestFeaturesResource.test_list_features.yaml
tests/integration/test_features_it.py

- Last test skipped, 405 returned for main operation

Implemented Features ITs

---

okta/constants.py
okta/utils.py
tests/integration/test_log_events_it.py
tests/integration/test_users_it.py
tests/mocks.py

- All currently skipped due to 405

Log Events Integration Tests

---

okta/constants.py
okta/models/identity_provider_policy.py
okta/models/o_auth_authorization_policy.py
okta/models/okta_sign_on_policy.py
okta/models/okta_sign_on_policy_rule.py
okta/models/password_policy.py
okta/models/password_policy_rule.py
okta/resource_clients/authorization_server_client.py
okta/resource_clients/policy_client.py
openapi/templates/constants.py.hbs
openapi/templates/index.js
openapi/templates/model.py.hbs
openapi/templates/partials/models/defaultMethod.py.hbs
openapi/templates/resource_client.py.hbs
tests/integration/cassettes/TestPoliciesResource.test_activate_deactivate_policy.yaml
tests/integration/cassettes/TestPoliciesResource.test_activate_deactivate_policy_rule.yaml
tests/integration/cassettes/TestPoliciesResource.test_create_get_password_policy_rule.yaml
tests/integration/cassettes/TestPoliciesResource.test_create_get_policy.yaml
tests/integration/cassettes/TestPoliciesResource.test_create_get_sign_on_policy.yaml
tests/integration/cassettes/TestPoliciesResource.test_create_get_sign_on_policy_rule.yaml
tests/integration/cassettes/TestPoliciesResource.test_create_get_sign_on_policy_with_group_conditions.yaml
tests/integration/cassettes/TestPoliciesResource.test_create_password_policy.yaml
tests/integration/cassettes/TestPoliciesResource.test_delete_policy.yaml
tests/integration/cassettes/TestPoliciesResource.test_delete_policy_rules.yaml
tests/integration/cassettes/TestPoliciesResource.test_list_policies_by_type.yaml
tests/integration/cassettes/TestPoliciesResource.test_list_policy_rules.yaml
tests/integration/cassettes/TestPoliciesResource.test_update_policy.yaml
tests/integration/cassettes/TestPoliciesResource.test_update_policy_rule.yaml
tests/integration/test_policies_it.py

The good stuff (actual tests) is found in `tests.integration.test_policies_it.py`. Other changes include code-gen changes to accommodate for these tests.
Thank you!

Policy integration tests

---

tests/integration/cassettes/TestIdentityProvidersResource.test_activate_deactivate_idp.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_add_get_facebook_idp.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_add_get_generic_idp.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_add_get_google_idp.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_add_get_linkedin_idp.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_clone_idp_signing_key.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_create_get_key.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_delete_idp.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_delete_key.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_generate_get_csr.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_generate_get_idp_signing_key.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_list_idp_signing_keys.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_list_idps.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_revoke_csr.yaml
tests/integration/cassettes/TestIdentityProvidersResource.test_update_idp.yaml
tests/integration/test_identity_providers.py

Tests for the Identity Provider resource, found in `tests.integration.test_identity_providers.py`

Completed IDP Integration Tests

---

okta/models/sms_template_translations.py
openapi/templates/model.py.hbs
tests/integration/cassettes/TestTemplatesResource.test_create_get_sms_template.yaml
tests/integration/cassettes/TestTemplatesResource.test_create_list_sms_templates.yaml
tests/integration/cassettes/TestTemplatesResource.test_delete_sms_template.yaml
tests/integration/cassettes/TestTemplatesResource.test_partial_update_sms_template.yaml
tests/integration/cassettes/TestTemplatesResource.test_update_sms_template.yaml
tests/integration/test_templates_it.py

Last set, I promise 😅 
Tests are in `tests.integration.test_templates_it.py`

Completed integration tests for SMS templates

---

README.md

Gabrielsroka patch 2

---

Makefile

Includes a make file to help with publishing

include make file

---

okta/resource_clients/application_client.py
openapi/templates/partials/models/defaultMethod.py.hbs
tests/unit/test_sign_on_modes.py

Made checkout from serhii_buniak/2021-02-16-custom-app-unknown-signon-OKTA-369792 to use the same file with predefined response test_sign_on_modes.py

Fix KeyError "signOnMode". OKTA-369135

---

okta/request_executor.py
tests/unit/test_client.py

Related to https://github.com/okta/okta-sdk-python/issues/177

Fix issue when custom HTTPClient is not used. OKTA-375294

---

okta/request_executor.py
tests/unit/test_client.py

Related to: https://github.com/okta/okta-sdk-python/issues/173

Handle aiohttp client errors. OKTA-374780

---

README.md
okta/oauth.py

Commits included:
Readme update - https://github.com/okta/okta-sdk-python/pull/181
Fix return value - https://github.com/okta/okta-sdk-python/pull/180, https://github.com/okta/okta-sdk-python/pull/182

Merge third-party contributions

---

okta/request_executor.py
tests/unit/test_request_executor.py

Related to https://github.com/okta/okta-sdk-python/issues/188

Fix request headers serializing. OKTA-380508

---

okta/request_executor.py
tests/unit/test_request_executor.py

Perform retry when HTTP status code is retryable: 429, 503, 504

Fix retry logic. OKTA-380999

---

okta/request_executor.py

Related to: https://github.com/okta/okta-sdk-python/issues/191

Log wait time when hit rate limit.

---

README.md
okta/models/user_profile.py
okta/resource_clients/group_client.py
okta/resource_clients/user_client.py
openapi/templates/model.py.hbs
openapi/templates/partials/models/defaultMethod.py.hbs
tests/unit/test_user_profile.py

Related also to GH issues: https://github.com/okta/okta-sdk-python/issues/201 and https://github.com/okta/okta-sdk-python/issues/202

Fix case issues with custom attributes. OKTA-393273, OKTA-384182

---

okta/api_client.py
okta/api_response.py

Related to #210, include PR #211

Fix pagination response, GH 210

---

okta/api_response.py
tests/unit/test_api_response.py

Related to https://github.com/okta/okta-sdk-python/issues/218

Add response headers to OktaAPIResponse object

---

okta/client.py
okta/models/__init__.py
okta/models/application_visibility.py
okta/models/org_contact_type.py
okta/models/org_contact_type_obj.py
okta/models/org_contact_user.py
okta/models/org_okta_communication_setting.py
okta/models/org_okta_support_setting.py
okta/models/org_okta_support_settings_obj.py
okta/models/org_preferences.py
okta/models/org_setting.py
okta/models/user_id_string.py
okta/resource_clients/org_client.py
tests/integration/cassettes/test_org_it/TestOrgResource.test_extend_okta_support.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_get_okta_communication_settings.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_get_okta_support_settings.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_get_org_contact_types.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_get_org_contact_user.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_get_org_preferences.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_get_org_settings.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_grant_revoke_okta_support.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_hide_okta_ui_footer.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_opt_in_users_to_okta_communication_emails.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_opt_out_users_from_okta_communication_emails.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_partial_setting_update.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_setting_update.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_show_okta_ui_footer.yaml
tests/integration/cassettes/test_org_it/TestOrgResource.test_update_org_contact_user.yaml
tests/integration/test_org_it.py

Related to https://oktainc.atlassian.net/browse/OKTA-420749 and #220

Add Org API resource

---

okta/config/config_validator.py
okta/error_messages.py
okta/request_executor.py
tests/unit/test_client.py

Related to: https://oktainc.atlassian.net/browse/OKTA-426996, https://github.com/okta/okta-sdk-python/issues/234

Allow Bearer auth

---

okta/resource_clients/authenticator_client.py
tests/integration/test_authenticators_it.py

Related to https://github.com/okta/okta-management-openapi-spec/pull/80

Update authenticators resource due to change in spec.

---

.travis.yml
setup.py
tox.ini

Python 3.9 Support - 3.10 should be soon :)

Python 3.9 Support

---

CHANGELOG.md

This commit reflects the change made in #205 in the CHANGELOG.

Reflect v1.7.0 breaking case change in CHANGELOG.md

---

okta/models/device_access_policy_rule_condition.py
openapi/package.json
openapi/yarn.lock

Re-generate SDK using openapi spec 2.9.2

---

.circleci/config.yml
.github/workflows/python-package.yml
okta/models/application_settings_application.py
okta/models/factor_type.py
regen.sh
requirements.txt
run_integration_tests.sh
run_unit_tests.sh
setup.py

Updated spec and regenerated, https://github.com/okta/okta-management-openapi-spec/pull/176 :
- Add missing properties to applicationsettingsapplication per the reference docs: https://developer.okta.com/docs/reference/api/apps/#settings-4
- Add signed_nonce factor type per the reference docs: https://developer.okta.com/docs/reference/api/factors/#factor-type
Fixes #360 
Fixes #312

OKTA-619080 & OKTA-588345 regen from latest spec
