okta/okta-sdk-python

okta/UsersClient.py

Hi everyone, I found something that I think it is a bug. The issue happen when you create a user without credentials
Steps to reproduce the issue:
1. Execute the following script (it is something similar of what is explained in the oktasdk [documentation](http://developer.okta.com/docs/sdk/core/python_api_sdk/quickstart.html#create-a-user))
```python
import okta
from okta.models.user import User
users_client = okta.UsersClient(os.environ['OKTA_BASE_URL'], os.environ['OKTA_API_TOKEN'])
user = User(login='ex@example.com', email='ex@example.com', firstName='saml', lastName='jackson')
users_client.create_user(user, activate=False)
```
2. Verify the user created in the Okta instance.
3. The user should be created with status STAGED but it is created with status PROVISIONED.
I only changed one …

:bug: Fixes create_user method for activate param 

---

okta/UserGroupsClient.py

Bug reported that `get_paged_groups` returns User instead of UserGroup
Resolves: OKTA-136640
Bacon: Test

Updates UserGroupsClient

---

tests/README.md
tests/conftest.py
tests/mocks.py

To unmock api calls set the following env variables:
```run_tests.sh
export OKTA_CLIENT_ORG_URL="{YOUR_ORG_URL}"
export OKTA_CLIENT_TOKEN="{YOUR_TOKEN}"
export MOCK_TESTS=True
export pytest_mock_client=True
pytest tests/integration/

Add env variable to mock/unmock api calls. OKTA-347119

---

okta/models/application_sign_on_mode.py
openapi/templates/model.py.hbs
tests/unit/test_sign_on_modes.py

How this single value Enum simulates MultiValueEnum:
```py
class MockMultiValueEnum(str, Enum):
VALUE_1 = 'value_1'
VALUE_2 = 'value_2'
VALUE_3 = 'value_3'
@classmethod
def _missing_(cls, value):
try:
return getattr(cls, value.upper())
except:
extend_enum(MockMultiValueEnum, value.upper(), value.lower())
return getattr(cls, value.upper())
print(repr(MockMultiValueEnum('value_4')))   # lowercase
print(repr(MockMultiValueEnum('VALUE_4'))) # uppercase
print(repr(MockMultiValueEnum('value_5')))   # lowercase
print(repr(MockMultiValueEnum('VALUE_5'))) # uppercase
```
Output:
```
<MockMultiValueEnum.VALUE_4: 'value_4'>
<MockMultiValueEnum.VALUE_4: 'value_4'>
<MockMultiValueEnum.VALUE_5: 'value_5'>
<MockMultiValueEnum.VALUE_5: 'value_5'>
```

Make dynamic enum for signOnMode. OKTA-369792

---

okta/oauth.py

Fix to ensure that the expected two item tuple format is returned by get_access_token when a client has an existing access_token cached. Was causing issues with calls to clear_user_sessions without this fix.

Fixing get_access_token to return tuple when access_token already exists

---

okta/oauth.py

In this Pull Request I correct a type of return value from oauth.py, get_access_token().
In request_executor.py function `create_request()` expects a tuple from `self._oauth.get_access_token()`
```
access_token, error = await self._oauth.get_access_token()
```
However in one specific case `get_access_token()` returns a string:
```
if self._access_token:
return self._access_token
```
Which causes an exception: 
>  File "site-packages/okta/request_executor.py", line 103, in create_request
access_token, error = await self._oauth.get_access_token()
ValueError: too many values to unpack (expected 2)

Return tuple from get_access_token()

---

okta/models/auto_login_application.py
okta/models/basic_auth_application.py
okta/models/bookmark_application.py
okta/models/browser_plugin_application.py
okta/models/open_id_connect_application.py
okta/models/saml_application.py
okta/models/secure_password_store_application.py
okta/models/ws_federation_application.py
openapi/templates/model.py.hbs

Related to #198 
This approach doesn't brake existing tests, for example this still works (tests/integration/test_applications_it.py, test_create_bookmark_app):
```py
found_app, _, err = await client.get_application(app.id)
assert err is None
assert found_app.label == APP_LABEL
assert found_app.sign_on_mode == models.ApplicationSignOnMode.BOOKMARK
```
Also, given enum comparable with strings:
```py
>>> models.ApplicationSignOnMode.BOOKMARK == 'BOOKMARK'
True
```

Make sign_on_mode of all apps instance of enum

---

README.md
okta/http_client.py
okta/request_executor.py
tests/unit/test_client.py
tests/unit/test_domains.py
tests/unit/test_request_executor.py
tests/unit/test_user_schema.py

This PR introduces new configuration option `sslContext`. Related to #255 
Usage example:
```py
import asyncio
import ssl
from okta.client import Client as OktaClient
async def main():
ssl_context = ssl.create_default_context()
client = OktaClient({"sslContext": ssl_context})
users, resp, err = await client.list_users()
print(users)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Allow custom ssl context.

---

README.md
okta/client.py
okta/http_client.py
okta/request_executor.py
tests/unit/test_client.py

Related to #267 
Add possibility to reuse http session by turning client into context manager (add `__aenter__` and `__aexit__`).
Using non-existent ids for testing purposes, performance tripled:
```py
import okta.client
import asyncio
import aiohttp
from time import time
async def main():
n = 20
start_time = time()
client = okta.client.Client()
for i in range(n):
resp = await client.get_user(f'{i}')
end_time = time()
print(f'no session: {end_time-start_time} sec')
start_time = time()
async with okta.client.Client() as client:
for i in range(n):
resp = await client.get_user(f'{i}')
end_time = time()
print(f'session: {end_time-start_time} sec')
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Add possibility to reuse http session. GH #267

---

okta/models/group_profile.py
openapi/templates/model.py.hbs
tests/integration/cassettes/test_groups_it/TestGroupsResource.test_group_profile_custom_attributes.yaml
tests/integration/test_groups_it.py

This PR allows to add custom attributes to GroupProfile object.
```py
group, okta_resp, err = await client.get_group(group_id)
```
Related to https://github.com/okta/okta-sdk-python/issues/279

Manage custom group profile attributes. Related to GH #279

---

.github/workflows/python-package.yml
.travis.yml
README.md
okta/models/application_credentials_o_auth_client.py
okta/models/o_auth_grant_type.py
okta/models/open_id_connect_application_issuer_mode.py
openapi/package.json
openapi/templates/index.js
openapi/templates/model.py.hbs
openapi/yarn.lock
setup.py

Problem:
Python SDK does not have the urn:ietf:params:oauth:grant-type:saml2-bearer [OAuthGrantType here](https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/models/o_auth_grant_type.py#L24-L36) that the customer cannot create such an OAuth2 Client using the Python SDK.
This PR updates the model generation within `model.py.hbs` to handle these cases after updates to the openAPI spec here: https://github.com/okta/okta-management-openapi-spec/pull/148
Generated code in OAuthGrantType now looks like this with newly added types:
JIRA: [OKTA-531005](https://oktainc.atlassian.net/browse/OKTA-531005)
Intended to Resolve: https://github.com/okta/okta-sdk-python/issues/298

Update to model generation for MultiValueEnum's

---

.circleci/config.yml
.gitignore
okta/request_executor.py
tests/unit/test_request_executor.py

For [OKTA-525379](https://oktainc.atlassian.net/browse/OKTA-525379):
- Problem has been raised in a number of GH issues that custom headers do not overwrite the default ones, especially the `Accept` header which defaults to `application/json`
- Fix problem where sometimes headers weren't being overwritten correctly
- Add test to verify

Support customized HTTP Request Headers

---

README.md
okta/jwt.py
okta/oauth.py
tests/mocks.py
tests/unit/test_jwt.py
tests/unit/test_oauth.py

Allow for JWT to be encoded with kid in headers when provided by user
Addressing https://github.com/okta/okta-sdk-python/issues/289

Specify kid when provided for JWT

---

tests/mocks.py
tests/unit/test_applications_ut.py
tests/unit/test_client.py
tests/unit/test_domains.py
tests/unit/test_request_executor.py
tests/unit/test_sign_on_modes.py

This PR should allow running all tests on any platform, depends on pytest-asyncio implementation

Remove all explicit event loop usage. Use pytest.mark.asyncio decorator

---

okta/logger.py
tests/unit/test_logger.py

Correctly set logger level
- to either given input log level
- or default to INFO if not provided
Resolving https://github.com/okta/okta-sdk-python/issues/292

Correctly set logger level in config

---

okta/jwt.py
requirements.txt

Resolving https://github.com/okta/okta-sdk-python/issues/306
- Removes conflict in `import Crypto` between `pycryptodome` and `pycrypto` packages by switching `pycryptodome` to `pycryptodomex`

Updating pycryptodome dependency to pycryptodomex

---

okta/api_response.py
openapi/templates/partials/models/defaultMethod.py.hbs

This PR can be merged after https://github.com/okta/okta-management-openapi-spec/pull/166 is resolved
Snippet used to test
```py
resp, err = await okta_client.preview_saml_app_metadata('{{appId}}')
print(resp)
print(resp.get_body())
```
Generates method:
```py
async def preview_saml_app_metadata(
self, appId, query_params={},
keep_empty_params=False
):
"""
Previews SAML metadata based on a specific key credenti
al for an application
Args:
app_id {str}
query_params {dict}: Map of query parameters for request
[query_params.kid] {str}
"""
http_method = "get".upper()
api_url = format_url(f"""
{self._base_url}
/api/v1/apps/{appId}/sso/saml/metadata
""")
if query_params:
encoded_query_params = urlencode(query_params)
api_url += f"/?{encoded_query_params}"
body = {}
headers = {}
form = {} …
```

Supporting the previewSAMLAppMetadata operation

---

okta/request_executor.py
tests/mocks.py
tests/unit/test_retry_logic.py

Addressing comments in https://github.com/okta/okta-sdk-python/issues/270
- Log when concurrent rate limit is hit
- Use async sleep for backoff
May need more discussions in the future regarding comments to set the concurrent rate limit through the SDK (https://github.com/okta/okta-sdk-python/issues/270#issuecomment-1141590502)

Improving support for multiple async requests

---

setup.py

- In latest release of SDK, the dependency `pycryptodomex` was added (in https://github.com/okta/okta-sdk-python/pull/345) but was not added to the setup.py, causing errors for users. This PR addresses that
Resolves: https://github.com/okta/okta-sdk-python/issues/350

Add missing dependency in setup.py

---

okta/api_response.py
okta/oauth.py

Remove the access token from request headers and cache when calling `clear_access_token`. Also update the request headers in `get_next` to prevent usage of old token. 
See [issue 363](https://github.com/okta/okta-sdk-python/issues/363) and [issue 359](https://github.com/okta/okta-sdk-python/issues/359)

Properly clear access token

---

requirements.txt

A new version of ecdsa was released on April 8, 2024.  This change updates the requirements.txt file to reference the new version of the component.

use latest ecdsa package to address vulnerability

---

okta/jwt.py
requirements.txt
setup.py
tests/mocks.py
tests/unit/test_jwt.py
tests/unit/test_oauth.py

This PR proposes to remove the `ecdsa` dependency completely by refactoring to use `jwcrypto` and `pyjwt`. This change is motivated by the [recent CVE](https://nvd.nist.gov/vuln/detail/CVE-2024-23342) that demonstrated the potential vulnerabilities in `ecdsa`. But regardless of any specific vuln, the maintainers of the `ecdsa` library have commented to suggest that it is not intended for "production use":
https://github.com/tlsfuzzer/python-ecdsa?tab=readme-ov-file#Security
By removing `python-jose` this PR does remove functionality from the `jwt` module (e.g. specifying alternate hash algorithms or JWT_OPTIONS). But as of today, these features appear to be unused. However please let me know if I'm mistaken here. As far as this PR is concerned though, the output of `JWT.create_token()` …

Remove ecdsa dependency

---

okta/oauth.py

#424 seems to break client creds based auth because it uses create_request() wrong, which will lead to a POST request to /oauth2/v1/token with a JSON body, content-type application/json. But this endpoint does not accept this content-type and returns with 'Accept and/or Content-Type headers likely do not match supported values.'. Instead it expects the content-type to be 'application/x-www-form-urlencoded', and the client assertion needs to be form encoded. This corrects that issue.

Fix client creds auth

---

requirements.txt
tests/integration/test_org_it.py
tests/integration/test_subscription_it.py

- Removed version from the test requirements.txt.
- Fixed failing integration unit test cases.

Allow latest aenum release

---

okta/models/o_auth_grant_type.py
tests/unit/test_applications_ut.py

- Added missing ENUM values to the OAuthGrantType.
- Added a unit test case to check the presence of values in the ENUM.
- Resolves: https://github.com/okta/okta-sdk-python/issues/396 https://oktainc.atlassian.net/browse/OKTA-733531

"Okta direct auth API grants" are not valid OAuthGrantType

---

okta/api_response.py
tests/unit/test_api_response.py

Fixed #435: added `data_type` parameter for `OktaAPIResponse`
The title and initial description blame `has_next`, but later comments clarify the issue is with inconsistent typing of results between pages. Added a unit test to show that the master branch currently has inconsistent types between pages. Resolved the issue by adding `data_type` parameter to `OktaAPIResponse` .
_I've emailed a signed CLA._

Fixed #435: added data_type parameter for OktaAPIResponse

---

okta/jwt.py

- Changed expiration time from 60 to 50 minutes in order to have a 10 minutes leeway in case of clock skew.
- Fixes: https://github.com/okta/okta-sdk-python/issues/382
- Fixes: Internal Ref#: https://oktainc.atlassian.net/browse/OKTA-917715

Reduce JWT token expiration time.

---

okta/client.py
okta/config/config_setter.py
okta/config/config_validator.py
okta/oauth.py
tests/unit/test_client.py
tests/unit/test_config_setter.py
tests/unit/test_config_validator.py
tests/unit/test_oauth.py

- Incorporated changes for PR https://github.com/okta/okta-sdk-python/pull/415.
- Added unit test cases for the changes made.
- Resolves: https://github.com/okta/okta-sdk-python/issues/359
- Resolves: https://github.com/okta/okta-sdk-python/issues/363
- Resolves: https://oktainc.atlassian.net/browse/OKTA-641384

Expire and renew the access token when using OAuth 2.0
